### ISSUE TITLE
Admin login: recaptcha "im not a robot" covers forgot password

### ISSUE THREAD

**Issue by m-overlund** [ProxiBlue/reCaptcha#12]
If recaptcha is set to "im not a robot" for admin login - it will cover the "forgot password" link.
![screen shot 2017-08-24 at 22 13 37](https://user-images.githubusercontent.com/504236/29686523-90cd035e-8919-11e7-842c-6699c81c875d.png)

Fix:
`display: inline-block;` added to the style will position it correctly.

**Comment by ProxiBlue** [comment]
Hi,

Can you show where you placed that? I am not finding the issue as described, so not sure if the placement is as per you fix.

+1 if you just do a PR :)

**Comment by ProxiBlue** [comment]
No further information provided. Cannot reproduce.

**Comment by m-overlund** [comment]
Related to #20 + #21
