### ISSUE TITLE
Translate reCaptcha texts problem

### ISSUE THREAD

**Issue by Pekkonen** [ProxiBlue/reCaptcha#13]
Hello.
I have 2 languages on my site and I need choice language for reCaptcha in admin accordingly.
I can't setup language for reCaptcha - then I select my website in "Current Configuration Scope" I don't appear CAPTCHA tab ((
![captcha1](https://user-images.githubusercontent.com/31384473/30423020-41ead48c-994a-11e7-921d-254b331864b4.jpg)
![captcha2](https://user-images.githubusercontent.com/31384473/30423019-41e9680e-994a-11e7-90eb-bc3b1f8d3973.jpg)

**Comment by ProxiBlue** [comment]
This is not a bug related to this module.

Magento core captcha works only at DEFAULT and WEBSITE scope. This is a limitation on capcha as implemented by magento core.

As noted from core config file: app/code/core/Mage/Captcha/etc/system.xml
```
                    <label>CAPTCHA</label>
                    <frontend_type>text</frontend_type>
                    <sort_order>50</sort_order>
                    <show_in_default>1</show_in_default>
                    <show_in_website>1</show_in_website>
                    <show_in_store>0</show_in_store>

```

You can see this same effect by installing a clean magento install, not include any modules, and then change the store scope.

**Comment by ProxiBlue** [comment]
https://github.com/ProxiBlue/reCaptcha/releases/tag/1.4.1 was fixed by https://github.com/ProxiBlue/reCaptcha/pull/14
