### ISSUE TITLE
Contacts page with reCaptcha doesn't work embedded in custom cms page

### ISSUE THREAD

**Issue by r2retail** [ProxiBlue/reCaptcha#18]
as title states, I have a working Contacts page with the Recaptcha. works without issues. but 
If I load the contacts page into a custom cms page in magento, the Recaptcha works, but the Recaptcha
won't render, and cannot be completed this way.

**Comment by ProxiBlue** [comment]
Hi. 

Can you give an example on how you are adding the contact us to the CMS page

**Comment by r2retail** [comment]
hey, 

The code used is : 

<p>{{block type="core/template" name="contactForm" form_action="/contacts/index/post" template="contacts/form.phtml"}}</p>

**Comment by ProxiBlue** [comment]
Hi,

with  

> but the Recaptcha won't render

do you mean that the reCaptcha is not display at all?

**Comment by r2retail** [comment]
It's not even loaded in the code. example of one of our webshops with issues: 

working contacts page:
https://www.sheisdifferent.nl/contacts

the code used as mentioned above. for the custom cms page:
https://www.sheisdifferent.nl/over-ons

**Comment by ProxiBlue** [comment]
Here you go: https://github.com/ProxiBlue/reCaptcha#use-in-cms-page

**Comment by r2retail** [comment]
Thank you for the quick reply, 

I have updated the module, I have used the new embedded code and added permissions for the custom block.  sadly this still doesn't work. 

as far as I can notice is that the captcha javascript isn't loaded on the cms page. 

I've used it on a different webshop that has the form embedded into a static block, and this works. 
So This might be a theme problem for the shop mentioned above, I'm still working on it, just wanted to give an update already.

**Comment by ProxiBlue** [comment]
No worries.

You may want to consider using an ajax form post, allowing the user to remain on the CMS page when submitting a contact  request.
You can achieve this easily by making a new template contact/form_ajax.phtml, and use that as the template file when embedding.

Here is a live exmaple: https://www.enjo.com.au/become-an-enjopreneur
