### ISSUE TITLE
Captcha not Working With Magento 193.x and 194xConatct Page.

### ISSUE THREAD

**Issue by vishalpatel14** [ProxiBlue/reCaptcha#29]
Hello Team,

We have install your extension but its not working with 1.9.3.x and 1.9.3.4 contactus page. can you provide some solution for the issue. This will be really helpful. It will be really appreciated.

**Comment by ProxiBlue** [comment]
Hi, 

Did you follow the guide in the readme, as well as the troubleshooting part?

**Comment by vishalpatel14** [comment]
Hello Team,

Yes we have follow all the troubleshooting part but still we dont have the captcha only on contactus page.

Also we have checked all the things more than 2 to 3 times still its not working on cpatcha page.

**Comment by vishalpatel14** [comment]
Hello Team,

We get now the captcha on contact form but now issue it it gives error when we submit with google captcha on contactus like Unable to submit your request. Please, try again later. 

Can you let me know what will be the issue might be?

**Comment by vishalpatel14** [comment]
Hello Team,

Here we have the logs for the same.

2018-12-10T09:51:54+00:00 DEBUG (7): Form ID: user_contact=>Array
(
    [name] => name
    [email] => e@e.com
    [telephone] => 23423
    [message] => dsfsfsdfds
    [g-recaptcha-response] => 
    [hideit] => 
)

2018-12-10T09:51:54+00:00 DEBUG (7): Form ID: user_contact=>No 'g-recaptcha-response' in request! - building 
2018-12-10T09:51:54+00:00 DEBUG (7): Form ID: user_contact=>sending to verify params of Array
(
    [privatekey] => 6LcZ1HIUAAAAAKJL5u6BPO-vGkmmK2wZBVsU84SD
    [challenge] => 
    [response] => 
)

2018-12-10T09:51:54+00:00 DEBUG (7): Form ID: user_contact=>Bad response from captcha gateway. we got 410
2018-12-10T09:51:54+00:00 DEBUG (7): Form ID: user_contact=>Exception fail : Bad response from captcha gateway. we got 410

**Comment by vishalpatel14** [comment]
Hello Team,

All the issue have been resolved. Can you please close this ticket. Thanks once again for prompt response.

**Comment by ProxiBlue** [comment]
Hi,

Happy to see you resolved this.
Can I ask what the final issue was? 

 Form ID: user_contact=>Bad response from captcha gateway. we got 410

What was wrong? I like to know, in case other users run into issue, they can ref this ticket.

**Comment by vishalpatel14** [comment]
Hello Team,

It was some kind of issue with the form template. Hence basically we have done 3 changes to achieve it.

1. I admin we have one option to show cpatcha we made it always.
2. We bring the layout.xml to current active theme.
3. We replace the full contact us form with latest form.phtml of Magento version. (I think we have issue over here hence the form was not being submitted)
