### ISSUE TITLE
Number of Unsuccessful Attempts to Login affects Contact us page

### ISSUE THREAD

**Issue by adarshkhatri** [ProxiBlue/reCaptcha#31]
First of all thanks for this great extension.

I was struggling to show recaptcha in my contact us page. Now I figured when I have Number of Unsuccessful Attempts to Login set to more than 0, then it doesn't show up. I must have 0.

This is little bit confusing since it ("Number of Unsuccessful Attempts to Login") is for login.

Hope this helps to others.

**Comment by ProxiBlue** [comment]
Hi,

NP, I use this on many of my clients sites, so tend to keep it working.

I never noticed that, and I agree it is a bug. Will get it sorted as soon as I can
