### ISSUE TITLE
Register form can't be resubmitted after Validation failure when using Invisible

### ISSUE THREAD

**Issue by r-martins** [ProxiBlue/reCaptcha#33]
Scenario/Steps to reproduce:
1. Set mode as Invisible
2. Mark Register During Checkout
3. Using OnePageCheckout (magento checkout), click on Register for step 1
4. Try to submit the form. You'll get many validation errors, like Password fields is required.
5. Try to fill the password fields (for example), and you'll be unable to move on to the next step. Looks like the Continue button is disabled or nothing happens.

Versions:
Magento 1.9.4.0
Php: 7.1.12
Module: 2.1.3

**Comment by ProxiBlue** [comment]
Hi,

Thank you for reporting this, and providing clear steps to reproduce.
I have managed to reproduce this, and will get an version out as soon as I figure out what is going on.

**Comment by ProxiBlue** [comment]
Hi,

I can no longer reproduce on 2.1.4.

https://github.com/ProxiBlue/reCaptcha/releases/tag/2.1.4

Please update and let me know if this works for you

**Comment by r-martins** [comment]
Hi @ProxiBlue. This was quick.
Thank you for fixing it so quickly. I was able to test 2.1.4 and see its now working.
