### ISSUE TITLE
Which released version will work with Magento 1.7?

### ISSUE THREAD

**Issue by lfolco** [ProxiBlue/reCaptcha#34]
I'd like to upgrade to the latest version but I believe it's not backward compatible for Magento 1.7. Can you tell me which release will work with 1.7?

**Comment by ProxiBlue** [comment]
Hi,

It is not really concerning just magento version, it involves what patches are installed.

I updated the README, to clarify:

If you have magento 1.9.4, *OR* you have Magento < 1.9.4 + SUPEE 10975 patch installed, you must use release 2.1.x or greater.
If you have Magento < 1.9.4 and not pacthes with SUPEE 10975, then you must use version 2.0.1 (the most up-to-date version prior to 1.9.4 and SUPEE 10975 patch)

Your *should* patch to SUPEE 10975 else your store is a security risk!
