### ISSUE TITLE
Is it compatible with Google Recaptcha v3?

### ISSUE THREAD

**Issue by rafaelpatro** [ProxiBlue/reCaptcha#37]
Hi guys! First of all thanks for this awesome extension.
Is it compatible with Google Recaptcha v3?

**Comment by ProxiBlue** [comment]
Hi,
Not (as yet)

I generally add in features as I need them, and I have no need for v3 at present

Feel free to contribute ;)

**Comment by Outdoorsman** [comment]
Yes it is compatible as of 2019-09-11.

**Comment by ProxiBlue** [comment]
@Outdoorsman 

I have not made this module compatible with v3 recaptcha, and have not once looked into this.
Can you elaborate why you note this? do you have a PR for work done making the code compatible?

**Comment by Outdoorsman** [comment]
Thank you @ProxiBlue for specifying I was mistakenly under the impressions that invisible reCAPTCHA was only  available in version 3.
