### ISSUE TITLE
Magento 1.9.4.3 throws undefined error on shopping cart

### ISSUE THREAD

**Issue by vishy93** [ProxiBlue/reCaptcha#41]
@ProxiBlue just updated to latest magento version, however sadly the following error is being thrown from this module now:

`Uncaught ReferenceError: Billing is not defined
    at window.reCaptchaCallback ((index):690)
    at $a (recaptcha__en_gb.js:518)
    at recaptcha__en_gb.js:521
    at a5 (recaptcha__en_gb.js:506)
    at l1 (recaptcha__en_gb.js:521)
    at recaptcha__en_gb.js:522
    at recaptcha__en_gb.js:541`

**Comment by ProxiBlue** [comment]
Hello,

Thanks for alerting me to this. I am having a look, by trying to reproduce.The noted js file recaptcha__en_gb.js is not in fact part of the module itself, but google recaptcha functionality code.

I am checking to see if I can reproduce.

Can you share the site this is happening on?

**Comment by vishy93** [comment]
Hey,

This weirdly has self corrected itself.
