### ISSUE TITLE
no changes on CAPTCHA settings after plugin install

### ISSUE THREAD

**Issue by kopitar** [ProxiBlue/reCaptcha#49]
After installing the plugin the core CAPTCHA settings in System > Advanced > Admin seem unaffected. 
[Screenshot](https://ibb.co/HPTXTP2)

Magento 1.9.2.4
reCaptcha plugin 2.3.4

- copied plugin contents to /app
- cleared cache

**Comment by ProxiBlue** [comment]
Hello,
Have you checked file permissions? ownership of files?

Can you confirm file locations are correct?

app/code/community/ProxiBlue/ReCaptcha
app/etc/modules/ProxiBlue_ReCaptcha.xml

Composer is the preferred install method.

**Comment by ProxiBlue** [comment]
Just had a look at your screenshot, and confuse by your ticket.
That screen is EXACTLY correct

I am not a robot is the recaptcha value produced by the module.
That looks like it is working.

What is it you are expecting to see?

**Comment by ProxiBlue** [comment]
closed due to no response.
