### ISSUE TITLE
Captcha not appearing on checkout

### ISSUE THREAD

**Issue by morgan** [ProxiBlue/reCaptcha#50]
Hello there!

We've successfully implemented reCaptcha and have it enabled across a variety of views. The one place we'd love to use it is on checkout. After a fair amount of inspection, it is unclear why the block is not being inserted.

Any thoughts?

Thanks ahead of time!

**Comment by ProxiBlue** [comment]
Hello,

Very likely a theme adjustment in a layout xml (checkout.xml or layout.xml)
In the module, the form is injected as part of the review:

https://github.com/ProxiBlue/reCaptcha/blob/master/app/design/frontend/base/default/layout/proxiblue_recaptcha.xml#L48

So I would say, issue likely that the parent block ```checkout.onepage.review.info.items.after``` is not being rendered.
