### ISSUE TITLE
I am not a robot fails on checkout if encounter sign-up error

### ISSUE THREAD

**Issue by siosphere** [ProxiBlue/reCaptcha#6]
When installed and setup to show on the cart page, when signing up as a new account, and doing the "I am not a Robot" captcha, if you encounter an error, like "email address is already registered", after fixing the problem, you are unable to continue creating an account, as the captcha will say it is invalid, but there is no way to re-do the captcha check on the frontend.

**Comment by ProxiBlue** [comment]
Hi.

Thanks for letting me know. Will look at this tiday

**Comment by ProxiBlue** [comment]
Hi,

Latest release fixes.
Sorry about the delay, but I was to busy making money ;)

**Comment by ProxiBlue** [comment]
@siosphere - just in case there was no notification sent by github, tagged you.

**Comment by siosphere** [comment]
Awesome thank you, I will pull the latest and install.
