### ISSUE TITLE
Question: Why is there Model rewrite?

### ISSUE THREAD

**Issue by adarshkhatri** [ProxiBlue/reCaptcha#9]
I am thinking of implementing your module in my EE 1.13 site. I was just checking it before I install. I can see you have rewritten one of the model, but I am unable to find it in core.

    <models>
            ............................
            <captcha>
                <rewrite>
                    <recaptcha>ProxiBlue_ReCaptcha_Model_Recaptcha</recaptcha>
                </rewrite>
            </captcha>
        </models>

Cannot find `Mage_Captcha_Model_Recaptcha` Model in core ([link](https://github.com/OpenMage/magento-mirror/tree/magento-1.9/app/code/core/Mage/Captcha/Model)). And more interestingly, your `ProxiBlue_ReCaptcha_Model_Recaptcha` model is not extending that class either. In fact, as I can see, this rewrite is not needed.

```
class ProxiBlue_ReCaptcha_Model_Recaptcha extends Mage_Captcha_Model_Zend implements Mage_Captcha_Model_Interface
{
```

Any particular reason for this? Also, will it work in EE 1.x site?

**Comment by ProxiBlue** [comment]
Hi. 

Please read the article linked in the readme.

The fact that the file does not exist is irrelavant - magento will do the 'rewrite' and load my class model in my module, as instructed by the rewrite. 

The extention is not tested in EE

**Comment by adarshkhatri** [comment]
HI ProxiBlue

Thanks for quick reply and more digging found the logic behind you are extending none existing core class.

**I am adding here to save time for any one trying to figure it out.**

https://magento.stackexchange.com/questions/30606/rewrite-in-custom-module-to-non-existing-core-class-model

When `Mage_Captcha_Helper_Data` calls this model, 

```
$type = $this->getConfigNode('type'); //returns recaptcha
Mage::getModel('captcha/' . $type); //becomes captcha/recaptcha

```

It redirects magento to **ProxiBlue_ReCaptcha_Model_Recaptcha** from rewrite system.

Your module looks nice and simple. I will install in EE and hopefully will work with no issues.
